// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfrwpqwifyqyvmyyycuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmcndwcXdpZnlxeXZteXl5Y3VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDk2NjIsImV4cCI6MjA2NzkyNTY2Mn0.Rqbx3H4EnaBj22iGvEQi7ywV3veNN4v9RoM0uZzPKls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Clear invalid session on initialization
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'TOKEN_REFRESHED' && !session) {
    // If token refresh failed, clear the session
    supabase.auth.signOut();
  }
});